### ISSUE TITLE
"Filter Actions" and "Server Traffic" windows send messages like query windows

### ISSUE THREAD

**Issue by Jay2k1** [Codeux-Software/Textual-Issues#12]
If you type something in the Filter Actions window, it is being sent to the server:
> 09Oct 20:15:51 << PRIVMSG Filter Actions :test

Which most likely results in
> Message(401): Filter No such nick/channel

Or, if someone is nicknamed filter, they get this:
> [20:15] &lt;Jay2k1&gt; Actions :test

Same happens with the Server Traffic window you get by using ```/debug raw on```:

> 09Oct 20:19:19  [Jay2k1]	test
> 09Oct 20:19:19 << PRIVMSG Server Traffic :test
> 09Oct 20:19:19 >> :hitchcock.freenode.net 401 Jay2k1 Server :No such nick/channel

Tested on 6.0.2 (Build 161001.16) (Standalone Version)

**Comment by emsquared** [comment]
This issue will be fixed in Textual 6.0.3

Relevant commit: https://github.com/Codeux-Software/Textual/commit/d1cdfb688d856379c7bad83ec8843c282b59568e
