### ISSUE TITLE
Chat filter scope: Channel list improvements

### ISSUE THREAD

**Issue by Jay2k1** [Codeux-Software/Textual-Issues#14]
* The triangles of networks cannot be used to collapse networks in the channel list of the chat filter; clicking them does not do anything at all.

* It would also be great if you could click on the channel name (or anywhere on its row/line for that matter) to toggle the selection instead of having to click inside the checkbox, because the checkbox is quite far away from the channel name and it's a bit hard to see which box belongs to which channel.

![image](https://cloud.githubusercontent.com/assets/2070503/19241075/441b37e4-8f0d-11e6-8199-47cd625efea5.png)

**Comment by emsquared** [comment]
This issue will be fixed in Textual 6.0.3

Relevant commit: https://github.com/Codeux-Software/Textual/commit/275db61b80cda89c62a5a27df6414654fd07702d
