### ISSUE TITLE
The IRC text color shortcut (Cmd+Opt+C) only works when you don't have text selected

### ISSUE THREAD

**Issue by iiiGerardoiii** [Codeux-Software/Textual-Issues#25]
If you select text from the text field and do Cmd+Opt+C, it will copy the text instead of bringing the text color palette.

This shortcut used to work on previous versions.

**Comment by dgw** [comment]
I haven't had this issue. Is it still present in 6.0.6?

**Comment by iiiGerardoiii** [comment]
I'm on 6.0.7-git and can still reproduce the issue.

1. Type something on the text field
2. Click Cmd+Option+C
3. **The color palette shows up**
4. Now select the text you just typed
5. Click Cmd+Option+C again
6. **The color palette doesn't show up anymore, Textual copies the text instead**

Video: https://a.pomf.cat/upfthm.mp4

**Comment by dgw** [comment]
I can't build from git myself (still on Yosemite), so someone else with El Capitan or later will have to try and reproduce.

**Comment by emsquared** [comment]
It is expected behavior that if color is already set when using Command Option C that it unsets the current color, not open the palette again. Why it is copying when it's supposed to be unset is beyond me. I haven't tried to replicate this issue yet, so it may not be doing that for me. I will update this when I do check.

**Comment by emsquared** [comment]
This issue will be corrected in 6.0.7

When a color is not set, it will display the palette. When a color is set, it will unset the color.

**Comment by iiiGerardoiii** [comment]
Testing 6.0.9-git, the issue has been corrected, thanks!

**Comment by iiiGerardoiii** [comment]
Issue came back on 6.0.10-git

**Comment by emsquared** [comment]
The keyboard shortcut for formatting changed in 6.0.10-git so that it no longer conflicts with other Textual and system keyboard shortcuts.

The new keyboard shortcuts are:
```Control Shift C for foreground color
Control Shift H for background color
Control Shift U for underline
Control Shift I for italic```

**Comment by iiiGerardoiii** [comment]
Oh I didn't know that, apologies.
