### ISSUE TITLE
Release a free version with a built-in coin miner

### ISSUE THREAD

**Issue by iiiGerardoiii** [Codeux-Software/Textual-Issues#35]
For the ones that are too lazy to build the application and/or are too poor to purchase it.

What do you think?

**Comment by dgw** [comment]
I think Codeux is above doing this.

**Comment by Jay2k1** [comment]
I can't wait for all the people in #textual to complain about their noisy fans and draining macbook batteries and high CPU usage... 😂

**Comment by emsquared** [comment]
While I think you for your creativity, it simply would not be possible because of performance. Textual is already burdened by its use of WebKit. A miner eating away at the CPU would not do it any favors.

Thank you for your suggestion at least.
