### ISSUE TITLE
Separate out typing from different windows

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [Codeux-Software/Textual-Issues#5]
When I type a message into one channel or query, and i don't hit enter, i goto another channel, and my text is there. Its very frustrating. I sometimes intentionally don't hit enter because maybe I'm switch back and forth from a query to a channel and don't want things mixed up.

**Comment by emsquared** [comment]
Issue closed because user is referring to a preference that already exists.

They were addressed in #textual on freenode
