### ISSUE TITLE
#historic_messages is only populated on launch

### ISSUE THREAD

**Issue by DominusExult** [Codeux-Software/Textual-Issues#7]
Unlike the previous .historic, #historic_messages is only populated on launch. So to test this or when you switch styles, you need to relaunch Textual to see the ease-in *and* to have the history in a different opacity than current messages.

This is counter intuitive since almost everything is reloaded on style reload or change.

At least the opacity level should be kept on style reload/change, the ease-in would be nice as well.

referencing b3c4c95b9ca66f098fe0aba924710d391c7e6a33

**Comment by emsquared** [comment]
This issue is closed by [38f28873afb21bad2255a53fc28de2d6e1867171](https://github.com/Codeux-Software/Textual/commit/38f28873afb21bad2255a53fc28de2d6e1867171)
