### ISSUE TITLE
"Mark All as Read" may freeze textual 6.0.0 and 6.0.1

### ISSUE THREAD

**Issue by dhellmann** [Codeux-Software/Textual-Issues#8]
Starting with the 6.0.0 release through the Mac App Store and continuing with 6.0.1 I have noticed a problem using the "Mark All as Read" command to clear the unread count in all channels. Occasionally it works fine, but more often it causes textual to become unresponsive (Activity Monitor reports it as not responding, it accepts no user input, and the cursor becomes the spinning beachball) so that I have to force-quit the app and restart it. The app does not appear to be consuming a lot of CPU during that time (it moves up and down in the Activity Monitor list and my overall CPU use does not spike).

I have 9 servers defined, but only 2 are active. Both servers connect to ZNC bouncers on different IRC networks. One has 9 channels and the other has 50.

I have not been able to confirm a pattern for when the function works and when it breaks. It *may* be related to how soon after relaunching the app I use it, because it seems to work if I relaunch and then quickly mark all as read. Timing may not be related, though.

**Comment by emsquared** [comment]
This issue is fixed in Textual 6.0.2. Will close it when that is live.

Thanks for the report!

**Comment by dhellmann** [comment]
Great, thanks!
